version: "3.8"
services:
  neo4j:
    image: neo4j:5.12
    container_name: neo4j
    ports:
      - "7474:7474"   # browser (HTTP)
      - "7687:7687"   # bolt
    environment:
      NEO4J_AUTH: "neo4j/neo4jpassword"
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
